# Generated by Django 3.2.8 on 2021-10-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_social_youtube_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
